# Read the CloudCannon documentation for more information on how to use this file:
# https://cloudcannon.com/documentation/articles/setting-global-configuration/?ssg=Next.js


# Base path to your source files, relative to the root folder of your repository.
source: src

output: out

# The locations of various types of files within your site.
# Each path is relative to your site's source folder.
paths:
  uploads: uploads

# Timezone of your site in IANA format. This is used by date and datetime inputs
# within the CloudCannon Data Editor.
timezone: Etc/UTC
